### ISSUE TITLE
[feature] hosted StreamLogic build toolchain

### ISSUE THREAD

**Issue by josuah** [brilliantlabsAR/monocle-fpga#11]
Given the GOWIN IDE is a command line tool that allows building the FPGA image from Linux among other systems.

Would it help to have a server that spins the GOWIN IDE and issue a binary?

Not sure the GOWIN license would allow something like this.

**Comment by siliconwitch** [comment]
This would be very convenient!

**Comment by siliconwitch** [comment]
Maybe this is something @sathibault would prefer to host? I imagine it would be something extendable for other vendor tools in the future such as Efinix, and other non-brilliant required platforms
