### ISSUE TITLE
Help, just a question: Which SPI mode does the ECX OLED use?

### ISSUE THREAD

**Issue by SinanAkkoyun** [brilliantlabsAR/monocle-fpga#16]
Hi! I would like to know what SPI mode the ECX OLED uses? I am working on an adapter board for a RPI and need to set registers for it to wake up from sleep mode.

In the datasheet, I can not find any information about serial mode... It would be awesome if you could help!

Thank you very much

**Comment by josuah** [comment]
Hello! Apologies for the long delay.
The SPI mode is, in this project, handled by the Microcontroler, where you would be able to check the CPOL and CPHA in use.
The datasheet suggests that the data is sampled during the rising edge of the clock, and updated during the falling edge of the clock.

This could be either MODE 0 or MODE 2.
